--Lista de precios de 350 productos escritos en el sistema 
SELECT PRECIOS.ID_PRODUCTO, CODIGO, PRODUCTO, MONTO
FROM PRODUCTOS, PRECIOS 
WHERE PRECIOS.ID_PRODUCTO = PRODUCTOS.ID_PRODUCTO; 
//
--Tenemos 420 distintos clientes diferentes registrados 
select COUNT(DISTINCT CLIENTE)
from E_CLIENTES   
//
--Tenemos 3232 distintos clientes en la base de datos que no son registrados 
select COUNT(DISTINCT CLIENTE)
from E_VENTAS  
//
--Para cargar registros de clientes al sistema. Desde aquí quite los valores duplicados con excel.
select ID_CLIENTE,Cliente, RUC, COMPROBANTE, FECHA 
from e_ventas 
WHERE CLIENTE <> 'MOSTRADOR' AND RUC <> 'XXX' AND RUC IS NOT NULL AND ID_CLIENTE = 375 and ruc <> ('') AND CLIENTE <>'GILCOPAR S.R.L' 
AND CLIENTE <> 'FACTURA DE VENTA CANCELADA PARA SEGUIR LA CORRELA'
--Clientes que ya se encuentran en la db después limpieza de datos en excel quitando los duplicados nuevamente en el archivo 'Clientes actu'
SELECT distinct CLIENTE, RUC 
FROM E_VENTAS
WHERE CLIENTE NOT IN ('AUTOMECANICA DM',
'JORGE JARA',
'JORGE GIMENEZ',
'KORSZYK',
'NILSA MOREIRA',
'PABLO SALINAS',
'PABLO MORENO',
'TALLER PACHIN',
'VICTOR SCHWARZ',
'JORGE VILLALBA',
'JUAN OLMEDO',
'AUTOMECANICA TEO',
'HUGO MARTINEZ',
'COMPAÑIA PINASQUEÑA',
'ALBERTO PALUMBO',
'HECTOR MOREL',
'AUTOMOTORES CITROPAR',
'TALLER IMPERIAL',
'OLIMPIC S.A',
'HUMBERTO FRETES',
'MERCOTEC SAE',
'VIMAR Y CIA S.A',
'LINCOLN S.A',
'JUAN CUBILLA',
'DE LOS ANGELES S.A',
'LUIS CANDIA',
'CLAUDIO BALANGIONE',
'SIXTO SOTO',
'CLINICA DEL AUTOMOVIL',
'LIONS CAR S.A',
'JUAN ROLON',
'CARLOS MARTINEZ',
'MARCOS DOLDAN', 
'RICARDO MACCHI',
'FIDEL ESPINOZA',
'JAVIER MAIDANA',
'TALLER BOTTANA',
'RPM SRL',
'TALLER MAN',
'CENTRO REPUESTOS',
'COPACO S.A',
'QUIMAFLEX SRL',
'EVEREST INGENIERIA SRL',
'ALBINO ACOSTA',
'FEPAM',
'NILDA VELAZQUEZ',
'TALLER EBEN EZER',
'AGP ETIQUETAS ADHESIVAS SRL',
'MANUEL MOLINAS',
'AUTOTECNICA SRL',
'NILSA MOREIRA',
'TALLER NASCAR',
'CHACO PARTS',
'MINISTERIO DE JUSTICIA',
'NORMA OJEDA',
'BRAHIAN ROA',
'JORGE RIVAS',
'VICTORIANO BENITEZ',
'ESSAP S.A',
'COMERCIAL IBAÑEZ',
'AVR AUTOMECANICA'
)

